/* TYPE PROJECT CONTEXT */
export const PROJECT_FORM = 'PROJECT_FORM';
export const GET_PROJECT = 'GET_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ERROR_PROJECT = 'ERROR_PROJECT';

/* TYPE TASK CONTEXT */
export const TASKS_PROJECT = 'TASKS_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const STATE_TASK = 'STATE_TASK';
export const ACTUAL_TASK = 'ACTUAL_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const CLEAN_TASK = 'CLEAN_TASK';

/* TYPE ALERT CONTEXT */
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

/* TYPE AUTH CONTEXT */
export const REGISTRATION_SUCCESFUL = 'REGISTRATION_SUCCESFUL';
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR';
export const GET_USER = 'GET_USER';
export const LOGIN_SUCCESFUL = 'LOGIN_SUCCESFUL';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOG_OUT = 'LOG_OUT';
